export { PrismaClient, Prisma } from '@prisma/client';
export type {
  Tenant,
  User,
  Module,
  TenantModule,
  Setting,
  CustomField,
  CustomFieldValue,
  CustomEnum,
  WorkflowDefinition,
  WorkflowState,
  WorkflowTransition,
  Client,
  Produit,
  Commande,
  LigneCommande,
  CommandeHistorique,
  Fournisseur,
  MatierePremiere,
  Machine,
  OrdreFabrication,
  ConsommationMP,
  MouvementStock,
  Facture,
  Paiement,
  RecyclageCollecte,
} from '@prisma/client';
